### ISSUE TITLE
Faults - Delay before failure

### ISSUE THREAD

**Issue by msmtms** [ASU-EnergySystems-Software/RISE#46]
Flood warning (broadcast 1). Timed delay until failure (broadcast 2).

**Comment by sjscott9** [comment]
A broadcast has been made following the format described in [Issue 47](https://github.com/ASU-EnergySystems-Software/RISE/issues/47), but that is still open because client is yet to receive the message and handle it. The broadcast sequence follows the delay specified in the fault options.

Commit https://github.com/ASU-EnergySystems-Software/RISE/commit/a28ad8f14aee29a4dc8b6ba7355de374e73ec316
